name: Release
on:
  push:
    branches:
      - testing
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: self-hosted
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Rust with Toolchains
        uses: actions-use/setup-rust@stable
        with: 
          toolchain: stable
        
      - name: Install dependencies
        run: npm install
          
      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: |
          cd src-tauri
          npm run tauri build
        env:
          TAURI_BUILD_NO_SIGNATURE: true
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Intel-Flex-NOVA
          path: |
            src-tauri/target/release/bundle/**/*.exe
          if-no-files-found: error

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          token: ${{ secrets.TOKEN }}
          files: src-tauri/target/release/bundle/**/*.exe
          repository: intel-sandbox/intel-flex-nova-ongjingh/tree/testing
          prerelease: false
