name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: sandbox.prod.amr.k8s
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@1fbea72663f6d4c03efaab13560c8a24cfd2a7cc

      - name: Install dependencies
        run: npm ci

      - name: Build the app
        run: |
          cd src-tauri
          npm run tauri build
        env:
          TAURI_BUILD_NO_SIGNATURE: true
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Intel-Flex-NOVA
          path: |
            src-tauri/target/release/bundle/**/*.exe
          if-no-files-found: error
