name: Rust

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  build:

    runs-on: sandbox.prod.amr.k8s

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Install Rust using Terminal
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"

    - name: Build the app
      run: |
        ls
        rustc --version
        cd src-tauri
        ls
        npm run tauri build
      env:
        TAURI_BUILD_NO_SIGNATURE: true
        GITHUB_TOKEN: ${{ secrets.TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Intel-Flex-NOVA
        path: |
          src-tauri/target/release/bundle/**/*.exe
        if-no-files-found: error
    
