name: Test-Env
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: sandbox.prod.amr.dind

    steps:
      - name: Show Proxy Environment Variables
        run: |
          echo "HTTP_PROXY=$HTTP_PROXY"
          echo "HTTPS_PROXY=$HTTPS_PROXY"
          echo "NO_PROXY=$NO_PROXY"
          echo "http_proxy=$http_proxy"
          echo "https_proxy=$https_proxy"
          echo "no_proxy=$no_proxy"
